using StalkerModLauncher.Models;
using StalkerModLauncher.Services;
using Xunit;

namespace StalkerModLauncher.Tests;

public sealed class Mo2ModListImporterTests : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(),
        "StalkerModLauncherTests",
        Guid.NewGuid().ToString("N"));

    [Fact]
    public void Import_ReversesMo2PriorityAndAppliesEnabledState()
    {
        var profile = CreateProfile("Fix", "High", "Low", "Middle");
        var modList = CreateModList(
            "# This file was automatically generated by Mod Organizer.",
            "+High",
            "-Middle",
            "+Low");

        var result = new Mo2ModListImporter().Import(profile, modList);

        Assert.Equal(["Fix", "Low", "Middle", "High"], profile.Mods.Select(mod => mod.Name));
        Assert.True(profile.Mods.Single(mod => mod.Name == "Low").IsEnabled);
        Assert.False(profile.Mods.Single(mod => mod.Name == "Middle").IsEnabled);
        Assert.True(profile.Mods.Single(mod => mod.Name == "High").IsEnabled);
        Assert.Equal(3, result.MatchedCount);
        Assert.Equal(1, result.EnabledStateChanges);
        Assert.Empty(result.MissingProfileMods);
        Assert.Equal(["Fix"], result.UnlistedLauncherMods);
    }

    [Fact]
    public void Import_MatchesFolderNameAndReportsMissingEntries()
    {
        var profile = new ModProfile();
        profile.Mods.Add(new ModEntry
        {
            Name = "Friendly name",
            SourcePath = Path.Combine(_root, "mods", "Actual MO2 Folder"),
            Order = 1
        });
        var modList = CreateModList("+Missing", "+Actual MO2 Folder");

        var result = new Mo2ModListImporter().Import(profile, modList);

        Assert.Equal(1, result.MatchedCount);
        Assert.Equal(["Missing"], result.MissingProfileMods);
        Assert.Empty(result.UnlistedLauncherMods);
    }

    private ModProfile CreateProfile(params string[] names)
    {
        var profile = new ModProfile();
        foreach (var name in names)
        {
            profile.Mods.Add(new ModEntry
            {
                Name = name,
                SourcePath = Path.Combine(_root, "mods", name),
                IsEnabled = true,
                Order = profile.Mods.Count + 1
            });
        }

        return profile;
    }

    private string CreateModList(params string[] lines)
    {
        Directory.CreateDirectory(_root);
        var path = Path.Combine(_root, $"{Guid.NewGuid():N}.txt");
        File.WriteAllLines(path, lines);
        return path;
    }

    public void Dispose()
    {
        if (Directory.Exists(_root))
        {
            Directory.Delete(_root, recursive: true);
        }
    }
}
